### ISSUE TITLE
Infinite scroll to right side in mobile

### ISSUE THREAD

**Issue by thaodx** [creativetimofficial/vue-paper-dashboard-pro#1]
Responsive layout got infinite scroll to right side in mobile.

**Comment by cristijora** [comment]
Can you share additional data please ?
Device, maybe a screenshot?

**Comment by cristijora** [comment]
I think you meant this right?
![image](https://user-images.githubusercontent.com/15955045/30159617-db1f23b6-93d1-11e7-829d-32b746a75a66.png)

If yes, this was already fixed yesterday and will be updated with the next 1.0.1 version .
If you want a quick fix, just change the footer text as this is what causes the horizontal scroll.

**Comment by thaodx** [comment]
Yes, it is @cristijora

**Comment by cristijora** [comment]
Then it is fixed and will be updated probably next week. As for your project, you probably will change the footer text anyway so it shouldn't be a problem unless you have lots of text there. You can specify some css options to wrap the text on multiple rows.

**Comment by thaodx** [comment]
Thank you @cristijora

**Comment by cristijora** [comment]
This has been fixed and released in v1.1.0
Feel free to download the [New version here](https://www.creative-tim.com/product/vue-paper-dashboard-pro)

and follow along the [Migration tips](https://cristijora.github.io/paper-dashboard-pro/documentation.html?selectedKind=General%20tips&selectedStory=Migration%20guide&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel) from previous version to the new version.
