### ISSUE TITLE
Guidelines for spinners

### ISSUE THREAD

**Issue by deivkk** [creativetimofficial/vue-paper-dashboard-pro#10]
Hi,

I would like to add some spinners while waiting for asynchronous requests sent to the server. Basically I am interested on adding spinner to Buttons and Tables (and graying-out the button and the current content of the table respectively). Since my knowledge of css is pretty basic (this is the main reason why I chose your template) I would like to know if there is any already existing solution in the template for it.

Thanks,

David

**Comment by cristijora** [comment]
Hey @deivkk 
A very simple way to do it is to add a loading icon from font awesome
```html
 <button type="button" class="btn btn-wd btn-success">
	<span class="btn-label">
	       <i class="fa fa-circle-o-notch fa-spin"></i>
	</span>
        Success
</button>
```

This will fit the design very well. If you need to conditionally display the loading icon and also disable the button you could extract this into a component
```html
 <button type="button" class="btn" :class="{disabled: loading}">
	<span class="btn-label">
	       <i v-if="loading" class="fa fa-circle-o-notch fa-spin"></i>
	</span>
        <slot></slot>
</button>


//js
props: {
 loading: Boolean
}
```

Usage:

```html
<loading-button :loading="true" class="btn-warning">
   Button text here
</loading-button>
```

**Comment by deivkk** [comment]
Great @cristijora, this is exactly what I was looking for!

Any hint for the spinner when loading content of a table? 

I have tried to use the same approach by adding the spinner on top of paginated table but the whole screen starts to blink when it is displayed

Thanks!

**Comment by deivkk** [comment]
I tried first to permanently display the spinner just to see how it looked, and it is when the screen blinked. 

However if the spinner is displayed only when searching for data then it works fine.

**Comment by cristijora** [comment]
Element-ui has a very simple loading directive for such things.
http://element.eleme.io/#/en-US/component/loading
You can place it on any tag. 
You need a little css to change the color
https://jsfiddle.net/28j0rs4x/3/
```css
.el-loading-spinner .path {
    stroke: red !important;
  }
```
