### ISSUE TITLE
 Menu icoin in the register screen on mobile

### ISSUE THREAD

**Issue by marcusos** [creativetimofficial/vue-paper-dashboard-pro#11]
Its showing the menu icon in the register screen on mobile and the menu is without any function. There is the possibility to hide the menu in the register screens on mobile mode?

Screenshot:
![c6de1395-c4fc-4616-9f09-bfffe1e41660](https://user-images.githubusercontent.com/4155254/30496477-dee99616-9a25-11e7-8c0f-20c3aaf904ee.jpg)

**Comment by cristijora** [comment]
Hi @marcusos . Thanks for using the product! 
On the Register, Login, Lock pages there is a navbar which has the markup simillar to this one
```html
<nav class="navbar navbar-transparent navbar-absolute">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle navbar-toggle-black" data-toggle="collapse"
                  data-target="#navigation-example-2">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar "></span>
            <span class="icon-bar "></span>
            <span class="icon-bar"></span>
          </button>
        </div>
      </div>
    </nav>
```
This is the menu button which appears on mobile. You can simply delete it from the markup if you don't need it.
```html
<button type="button" class="navbar-toggle navbar-toggle-black" data-toggle="collapse"
                  data-target="#navigation-example-2">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar "></span>
            <span class="icon-bar "></span>
            <span class="icon-bar"></span>
</button>
```

Hope it helps. Happy coding :)

**Comment by marcusos** [comment]
@cristijora Thank you!
