### ISSUE TITLE
[Question] Element UI component

### ISSUE THREAD

**Issue by donPuerto** [creativetimofficial/vue-paper-dashboard-pro#20]
is all Element UI component can be used on vue paper dashboard?

**Comment by cristijora** [comment]
Hi @donPuerto 
Short answer is yes, but you might want to style the extra components you want to use to keep the same paper style. You can see for example how select components or datepickers are styled 

`_select.scss` 
`_datetime-picker.scss`

It's not hard to style element-ui components. You can inspect in chrome the component and see what are it's classes. Element-UI uses BEM for css so you can use
`.el-component-name` classes :)

Hope this information helps.
