### ISSUE TITLE
Datepicker and vee-validate integration

### ISSUE THREAD

**Issue by dromero93** [creativetimofficial/vue-paper-dashboard-pro#22]
Hey, thanks for the great job! 
So I'm trying to integrate both components (element ui date picker and vee-validate) I'm dealing with format issues.
I can format the visible value of the datepicker element but not the one saved in the v-model.
 for example:

`<el-date-picker  type="date" placeholder="Pick a day"
                                                     v-model="beginDate"
                                                     format="dd-MM-yyyy"
                                                     v-validate="modelValidations.beginDate"
                                                     name="beginDate">
                                    </el-date-picker>`

So the shown date in the element is in that specific format (dd-MM-yyyy), but in the beginDate variable the format is very different.

for example: the element visible value is : 15/10/2017
the beginDate value is : Sun Oct 15 2017 22:43:35 GMT-0600 (CST)

the problem is when I tried to validate, my validations rules are
`beginDate: {
                        required: true,
                        date_format: 'DD-MM-YYYY',
                        before: 'formattedEndDate'
                    }`

So keeps failing for the format.

**Comment by cristijora** [comment]
Hi @dromero93 
I tried to do it quickly but came across the same issue.
Opened an [issue on vee-validate repo](https://github.com/baianat/vee-validate/issues/901)
The author usually responds very fast so we might get an answer soon

**Comment by cristijora** [comment]
@dromero93 This is addressed in vee-validate already and should work in the next release. I can't say exactly when but from the release logs, the rc versions of vee validate are released every couple of days or with a week difference between them

**Comment by dromero93** [comment]
Thanks @cristijora , so I'll wait for next release, or try to make a work around.


Thanks again

**Comment by cristijora** [comment]
Hi again @dromero93 
The date format issue has been addressed in the latest vee-validate version.
https://codesandbox.io/s/133rx7lvo7

A new version of vue-paper-dashboard-pro will come this week with an upgrade to element-ui 2.0
which has support for so called `value-format` on date-pickers. 
https://codesandbox.io/s/73mnjjp9kj

**Comment by cristijora** [comment]
Closing this as it didn't require changes on the dashboard

**Comment by freddysidauruk** [comment]
what if i didn't use v-model cause for some reason, i use :value how can i validation the date picker ?
