### ISSUE TITLE
Failed to run vue-pdp-v1.0.0, Can’t find variable: Promise

### ISSUE THREAD

**Issue by liuhahi** [creativetimofficial/vue-paper-dashboard-pro#23]
### Environment:
| Node   |      Mac OS      |  yarn |
|----------|:-------------:|------:|
| v6.11.4  |  10.12.6 | v1.2.1 |

### Step to reproduce the issue:
1. `yarn install `
2. `yarn test`

### Error messages:
yarn run v1.2.1
$ npm run unit && npm run e2e

> vue-paper-dashboard-pro@1.0.0 unit /Users/liuyang/Downloads/vue-pdp-v1.0.0
> cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run

16 10 2017 16:23:36.104:INFO [karma]: Karma v1.4.1 server started at http://0.0.0.0:9876/
16 10 2017 16:23:36.113:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
16 10 2017 16:23:36.146:INFO [launcher]: Starting browser PhantomJS
16 10 2017 16:23:41.014:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket K1WjW91vw9TZBzuhAAAA with id 91228063
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can’t find variable: Promise
  at webpack:/webpack/bootstrap%20028b73458bc3066e9352:91:0 <- index.js:92

PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 0 of 0 ERROR (0.443 secs / 0 secs)

INFO LOG: ’You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-paper-dashboard-pro@1.0.0 unit: `cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-paper-dashboard-pro@1.0.0 unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/liuyang/.npm/_logs/2017-10-16T08_23_41_519Z-debug.log
error Command failed with exit code 1.

**Comment by cristijora** [comment]
Hi @liuhahi . The tests had some issues in the first version. Those issues have been addressed already and we upgraded to the latest vue-cli changes. We will upgrade the dashboard soon (probably next week). 
I will try to post a fix later on here for the current version.

**Comment by liuhahi** [comment]
@cristijora okay!

**Comment by sfdye** [comment]
+1 for this issue.

Just purchased this product. However, I found the documentation to be very simple. There is not much information on how to use it and surprisingly the tests didn't pass!

@cristijora 
1. How do you suggest to integrate `vue-pdp` into an existing project, instead of using it directly?

2. Is there a good strategy to handle future product update? For example, if my project is already using `vue-pdp` and there is a updated version with some features I am dying to try out. How do I go about applying the changes? I understand it won't be as simple as changing the version number like when upgrading a npm package.

**Comment by cristijora** [comment]
@sfdye I understand you concert. I will add some steps on how to upgrade. Upgrading would basically require copying config files (webpack setup), and the `components` and `assets` folders.

From the next version on, the upgrades will be easier and will require:
- Optionally copying a `webpack.custom.js` config which willl contain only paper-dashboard-pro stuff for webpacl
- Copying components and assets folder.

If you guys have any suggestions I am open to pretty much anything as long as it's better.

**Comment by sfdye** [comment]
@cristijora Cool! I think `webpack.custom.js` is definitely a better idea. Can't wait for the 2nd release 🚢

**Comment by sfdye** [comment]
@cristijora Any update on this please?

**Comment by sfdye** [comment]
Still no word on v1.1.0?

**Comment by cristijora** [comment]
Sorry for the long delay @sfdye (was busy with a hackathon) The release will be this week.

**Comment by sfdye** [comment]
@cristijora cool, how was the 🍕 ? Can't wait for the new release 😎

**Comment by cristijora** [comment]
Actually won a prize with a solution based on this exact template 🙌

**Comment by sfdye** [comment]
💯

**Comment by cristijora** [comment]
@sfdye @liuhahi 
This has been fixed and released in v1.1.0
Feel free to download the [New version here](https://www.creative-tim.com/product/vue-paper-dashboard-pro) and follow along the [Migration tips](https://cristijora.github.io/paper-dashboard-pro/documentation.html?selectedKind=General%20tips&selectedStory=Migration%20guide&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel) from previous version to the new version.

We've added  a couple more tests and will continue to add more tests for the custom components in the next versions.
