### ISSUE TITLE
Remove movingArrow and "active" menu Item class

### ISSUE THREAD

**Issue by JuanesAdriano** [creativetimofficial/vue-paper-dashboard-pro#24]
Hey there!
i'm developing a big interface with Vue Paper pro and at some point of the project we did implement a dynamic  'Taber' to display opened components(something like chrome tabs), and now we don't want to use the movingArrow and the "active" menu Item because it just does not make sense to show which 
component is active in the menu anymore; the active item is now the active tab with the wanted component and it's already shown in the current active tab.

I'm trying to just disable the moving arrow and the active item on the menu itens.
Can you help me with that please?

Also, nice work with that template! loving to work with it.

**Comment by cristijora** [comment]
Hi @JuanesAdriano 
First of all, glad you find the product useful! 

The active class is used in combination with vue-router 
In main js where you setup vue-router there should be something like this
```js
const router = new VueRouter({
  routes, // short for routes: routes
  linkActiveClass: 'active'
})
```
You can either change the `active` to something else. This will basically disable styles for links in the sidebar when a route is active.
If this is not a good option you could go inside `_sidebar-and-main.panel.scss` line 126
```css
&.active > a{
          color: $primary-color;
          opacity: 1;
 }
```

And change this piece of code to what you need.

Regarding arrow, that is from css only. You can find the css for that part inside `_responsive.scss` 
- line 105 to line 130 (for desktop > 992px)
- line 241 to line 262 (for tablet and mobile <992px)

You could simple remove that code and the arrow will not appear.

**Comment by JuanesAdriano** [comment]
Thanks man, keep the good work!
