### ISSUE TITLE
Element UI 2

### ISSUE THREAD

**Issue by LokiOfNZ** [creativetimofficial/vue-paper-dashboard-pro#25]
Do you have any upgrade path or patch for Element UI 2.x? It doesn't seem as straight forward as updating the dependency version in package.json :)

**Comment by cristijora** [comment]
Hi @LokiOfNZ 
The template was updated/upgraded to a new version 2 days ago.
The update includes an update to element-ui 2.0.3.
You can find some details [here](https://cristijora.github.io/paper-dashboard-pro/documentation.html?knob-Toggle%20first%20checkbox=false&knob-Disable%20first%20checkbox=false&knob-Change%20text%20for%20first%20checkbox=Unchecked&selectedKind=General%20tips&selectedStory=Migration%20guide&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel)

If you don't have the time and patience to do the update then you could go for a quick upgrade like this:
 - Update element package to latest one
 - Change `theme-default` to `theme-chalk` in the plugins section inside `.babelrc` file

Copy over the sass files from v1.1.0 to your project (some of them are updates for element 2.0). There is also a file called `element_variables.scss` which is used for theming.

**Comment by LokiOfNZ** [comment]
Ah snap, I only started the project 5 days ago so didn't see the update!

FYI I've gone through the migration guide in full, looks all good except I had to change line 49 of WorldMap.vue to add the '-next' onto the end of 'jvectormap' to get it to compile?

**Comment by cristijora** [comment]
@LokiOfNZ Thanks for pointing that out. You could've replaced the WorldMap with the new one if you use it.
Indeed, `-next` has to be added there since the plugin for map was updated (the previous one was no longer maintained)

**Comment by cristijora** [comment]
Hey @LokiOfNZ 
Same thing as WorldMap, you could copy those files from the new version if you use them, or simply add keys where they are missing.
`:key="task.title"`
