### ISSUE TITLE
Color yellow background color typo error 

### ISSUE THREAD

**Issue by liuhahi** [creativetimofficial/vue-paper-dashboard-pro#27]
There is a typo error in _cards.scss which cause color yellow not defined 
![screen shot 2017-11-15 at 10 58 40 am](https://user-images.githubusercontent.com/2950675/32816520-0a503730-c9f4-11e7-898a-111dea02ea9a.png)

**Comment by cristijora** [comment]
Thanks a lot @liuhahi for that. Will be fixed in the next update
Should be `data-background-color` instead of `data-bakcground-color`
@alexandru-paduraru This might be useful for you guys as well for the html version
