### ISSUE TITLE
Missing logo on Mobile Menu

### ISSUE THREAD

**Issue by peter3099** [creativetimofficial/vue-paper-dashboard-pro#31]
Hello

When you switch from normal view to mobile view the Vue Logo doesn't show at the top, any ideas how to solve it?

![image](https://user-images.githubusercontent.com/22412633/34297038-6adf1860-e6f4-11e7-9bb5-0d9a691a5d0c.png)

Thanks

**Comment by cristijora** [comment]
Hi @peter3099 Thanks for reporting. This was intended (not to show the logo on mobile)

If you want it visible, you can go in `_responsive.scss` inside `src/assets/sass/paper` folder
and delete this
```css
a.logo-mini{
        display: none;
}
```

on line `295` or simply change `display: none` to `display: block`.

**Comment by peter3099** [comment]
Thanks Cristi
