### ISSUE TITLE
Request: Extend the menu

### ISSUE THREAD

**Issue by KH-IT** [creativetimofficial/vue-paper-dashboard-pro#32]
First of all great work with this template easy to understand.
I was thinking to extend the menu but maybe it was something that can be done within the vue-paper-dashboard-pro template. 
Problem: 
My menu is growing I need more and more multiple levels in the menu. 
Possible solution:
Now you have an arrow down and then the menu go open.
If there would be a arrow right that opens in the "menu region body" the subitems of that menu.
And foresee a footer that stay when navigating.
My explanation is not very clear but in my amateur picture it's a little bit more clearer.
I am not good at UX so I hope this can be implemented on some manner.
![extention](https://user-images.githubusercontent.com/33102056/34358201-fb6fe0a6-ea4d-11e7-8da4-6a25fa50546b.png)

**Comment by cristijora** [comment]
Hi @KH-IT Sorry for the late response here. No worries about the explanation. I understood what you mean.
Regarding the request, unfortunately this would imply a new design which I'm not sure we'd like to change in this case.

As an alternative you can have multiple level menus (e.g 3 levels) by specifying the `children` array.
You can find an example here. https://github.com/creativetimofficial/vue-paper-dashboard-pro/blob/master/CHANGELOG.md#110-2017-11-07

Note that this feature is available only with the 1.1.0 release from November. If you have the previous release you can follow the [Migration guide](http://vuejs.creative-tim.com/paper-dashboard-pro/documentation.html?selectedKind=General%20tips&selectedStory=Migration%20guide&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel) from 1.0.0 to 1.1.0

**Comment by KH-IT** [comment]
I have thought about it and I will go for the solution that you offered of the 3 level menu it's already implemented. I had to read the documentation then I was gone for that solution in the first place. 

Maybe it will be handy that it's visible in the demo application for other people that they can see it in action immeditely.

Thank you very much for your response!
