### ISSUE TITLE
running "npm run dev" results in errors.

### ISSUE THREAD

**Issue by Hodles** [creativetimofficial/vue-paper-dashboard-pro#36]
> Starting dev server...

 ERROR  Failed to compile with 35 errors                                                                                 11:44:21 PM

 error  in ./src/App.vue

Syntax Error: Unexpected token {

 @ ./src/main.js 8:0-28
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/UIComponents/Dropdown.vue

Syntax Error: Unexpected token {

 @ ./src/gloablComponents.js 2:0-62
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/UIComponents/Inputs/formGroupInput.vue

Syntax Error: Unexpected token {

 @ ./src/gloablComponents.js 1:0-74
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/UIComponents/Inputs/Checkbox.vue

Syntax Error: Unexpected token {

 @ ./src/gloablComponents.js 3:0-69
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/UIComponents/Inputs/Radio.vue

Syntax Error: Unexpected token {

 @ ./src/gloablComponents.js 4:0-63
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/GeneralViews/NotFoundPage.vue

Syntax Error: Unexpected token {

 @ ./src/routes/routes.js 3:0-67
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Dashboard/Layout/DashboardLayout.vue

Syntax Error: Unexpected token {

 @ ./src/routes/routes.js 1:0-81
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Dashboard/Views/Charts.vue

Syntax Error: Unexpected token {

 @ ./src/routes/routes.js 37:0-63
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Dashboard/Views/Dashboard/Overview.vue

Syntax Error: Unexpected token {

 @ ./src/routes/routes.js 5:0-77
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Dashboard/Views/Dashboard/Stats.vue

Syntax Error: Unexpected token {

 @ ./src/routes/routes.js 6:0-71
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Dashboard/Views/Pages/UserProfile.vue

Syntax Error: Unexpected token {

 @ ./src/routes/routes.js 8:0-72
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Dashboard/Views/Pages/Login.vue

Syntax Error: Unexpected token {

 @ ./src/routes/routes.js 10:0-67
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Dashboard/Views/Pages/TimeLinePage.vue

Syntax Error: Unexpected token {

 @ ./src/routes/routes.js 9:0-77
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Dashboard/Views/Pages/Register.vue

Syntax Error: Unexpected token {

 @ ./src/routes/routes.js 11:0-73
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Dashboard/Views/Pages/Lock.vue

Syntax Error: Unexpected token {

 @ ./src/routes/routes.js 12:0-65
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Dashboard/Views/Components/GridSystem.vue

Syntax Error: Unexpected token {

 @ ./src/routes/routes.js 15:0-82
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Dashboard/Views/Components/Buttons.vue

Syntax Error: Unexpected token {

 @ ./src/routes/routes.js 14:0-76
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Dashboard/Views/Components/Panels.vue

Syntax Error: Unexpected token {

 @ ./src/routes/routes.js 16:0-74
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Dashboard/Views/Components/SweetAlert.vue

Syntax Error: Unexpected token {

 @ ./src/routes/routes.js 17:0-82
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Dashboard/Views/Components/Notifications.vue

Syntax Error: Unexpected token {

 @ ./src/routes/routes.js 18:0-88
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Dashboard/Views/Components/Icons.vue

Syntax Error: Unexpected token {

 @ ./src/routes/routes.js 19:0-72
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Dashboard/Views/Components/Typography.vue

Syntax Error: Unexpected token {

 @ ./src/routes/routes.js 20:0-82
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Dashboard/Views/Forms/ExtendedForms.vue

Syntax Error: Unexpected token {

 @ ./src/routes/routes.js 23:0-83
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Dashboard/Views/Forms/ValidationForms.vue

Syntax Error: Unexpected token {

 @ ./src/routes/routes.js 24:0-87
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Dashboard/Views/Forms/RegularForms.vue

Syntax Error: Unexpected token {

 @ ./src/routes/routes.js 22:0-81
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Dashboard/Views/Forms/Wizard.vue

Syntax Error: Unexpected token {

 @ ./src/routes/routes.js 25:0-69
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Dashboard/Views/Tables/RegularTables.vue

Syntax Error: Unexpected token {

 @ ./src/routes/routes.js 27:0-84
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Dashboard/Views/Tables/ExtendedTables.vue

Syntax Error: Unexpected token {

 @ ./src/routes/routes.js 28:0-86
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Dashboard/Views/Tables/PaginatedTables.vue

Syntax Error: Unexpected token {

 @ ./src/routes/routes.js 29:0-88
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Dashboard/Views/Maps/GoogleMaps.vue

Syntax Error: Unexpected token {

 @ ./src/routes/routes.js 31:0-76
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Dashboard/Views/Maps/FullScreenMap.vue

Syntax Error: Unexpected token {

 @ ./src/routes/routes.js 32:0-82
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Dashboard/Views/Maps/VectorMapsPage.vue

Syntax Error: Unexpected token {

 @ ./src/routes/routes.js 33:0-80
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Dashboard/Views/Calendar/CalendarRoute.vue

Syntax Error: Unexpected token {

 @ ./src/routes/routes.js 35:0-81
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/UIComponents/SidebarPlugin/SideBar.vue

Syntax Error: Unexpected token {

 @ ./src/components/UIComponents/SidebarPlugin/index.js 1:0-36
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/UIComponents/SidebarPlugin/SidebarItem.vue

Syntax Error: Unexpected token {

 @ ./src/components/UIComponents/SidebarPlugin/index.js 2:0-44
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

> Listening at http://localhost:8000

**Comment by cristijora** [comment]
Hi @Hodles 
Would help a lot to post here 
1. Node version
2. OS platform (windows/linux)

Things to look/try 
1. Check if you have `.babelrc` file in your projects (there were some cases when it was not downloaded)
2. Make sure you ran `npm install` or `yarn install` and all packages were installed.

**Comment by Hodles** [comment]
I was running a very old version of node.   I should have checked before posting.  thanks for your help
