### ISSUE TITLE
Built files not being injected

### ISSUE THREAD

**Issue by dniccum** [creativetimofficial/vue-paper-dashboard-pro#40]
After running the `yarn` installation command, followed by the `yarn run dev` command, the application serves up a blank white page. The index.html file that is in the root of the project indicates that all scripts will be dynamically injected, but it appears that nothing is happening.

There are no errors during the Webkit compilation step.

**Comment by cristijora** [comment]
Hi @dniccum 
Do you have any errors in the terminal when running (run dev) ?
Also do you mind sharing your 
- Node version
- Operating System type

**Comment by dniccum** [comment]
After opening up the project again and re-built the project to send some screenshots, everything appears to be working as expected. I'm not sure as to why I had issues the first time around. Apologies for the false alarm.
