### ISSUE TITLE
how to detect changes about p-switch

### ISSUE THREAD

**Issue by YeoDaeHwi** [creativetimofficial/vue-paper-dashboard-pro#41]
Hello, 

I applied the data received from the http request to the table p-switch. 

<img width="799" alt="2018-04-11 7 42 32" src="https://user-images.githubusercontent.com/16669599/38612089-92ddbeca-3dc0-11e8-983f-ded239ed056c.png">

I have to get the user input and pass the changed switch values back to the server.

but.. 

I don't know how to detect a  p-switch event on a child component.

please help me..

regard,

**Comment by cristijora** [comment]
Hi @YeoDaeHwi Thanks for using our products first of all. 
I will try to be as explicit as possible here. If you don't know about this, `v-model` is a shorthand to `:value="myValue" @input="evt => myValue = evt.target.value"` in most cases. 

In our case, the switch component uses `v-model`. You could use that if you don't need explicit handling, or you could use the explicit syntax with prop and event like this:
`<p-switch :value="switchValue" @input="handleSwitchValue">`

Now if the switch is in the table context, you could extend this a bit so you can pass in the row info

```
<p-switch :value="row.switchValue" @input="(value) => handleSwitchValue(row, value)">


handleSwitchValue(row, value){
// your custom logic here then make sure to set the value
row.switchValue = value;
}
```

`row` in this case would be the table row. You can access it easily with element-ui table column and scoped slots.

**Comment by YeoDaeHwi** [comment]
Hi, cristijora

Your reply was very helpful indeed.

I would like to say thank you very much for this. ; )
