### ISSUE TITLE
Can't change the favicon

### ISSUE THREAD

**Issue by Sergeon** [creativetimofficial/vue-paper-dashboard-pro#43]
Hi folks! This is my first time posting an issue in this project. [My company](http://www.hetikus.com) decided to use this dashboard template for our next project, so I guess I'll be posting here from time to time.

My issue now is pretty silly, but I just can't change the favicon 😅. I deleted the old `favicon.ico` with the Vue.js logo and added a new `.ico` with ours. However, whenever I run the project, the Vue.js logo still displays as the favicon.

In the `<head>` tag of the page I see that the `<link>` tag in the `index.html` file now appears commented out, and two more `<link>` tags appear pointing to `/img/icons/favicon-32x32.png` and `16x16.png`. I guess it is webpack magic.

My `<head>` tag displays like:

![image](https://user-images.githubusercontent.com/6699334/39624554-10c9e4a4-4f9a-11e8-94bb-6bf98a299861.png)

Things I already did:

- rm `node_modules` and `npm install` again.
- Clear cache/load from incognito.
- Absolutely check that my `public/favicon.ico` is our icon and not the vue's one.

Any advice? help in advance.

**Comment by cristijora** [comment]
Hello @Sergeon 
Sorry for the long wait here. I've been on vacation for couple of days.
So from what I see here, the link to the favicon is a bit wrong 
Here's the original link 
```js
<link rel="icon" type="image/png" sizes="96x96" href="static/img/favicon.png">
```
As you can see it starts with `static` which points to the `static` folder inside the project. Make sure you have it in the same way.
If you have a wrong link for favicon, most browsers will fallback to some icon that you recently used for localhost or where your app is started. 
Let me know if that helps

**Comment by Sergeon** [comment]
Thank you, now it works. :-D
