### ISSUE TITLE
dropdown-toggle mause hover/click problem if it is above a card

### ISSUE THREAD

**Issue by marcusos** [creativetimofficial/vue-paper-dashboard-pro#5]
In the screen (for example): https://cristijora.github.io/paper-dashboard-pro/#/admin/stats

I can not select/hover the 'Notification 2' item in the  dropdown-toggle

I think  that the element 'card-header' is causing this behavior to the dropdown-toggle element.

My browser: google chrome 60.0.3112.113

Print:
![error](https://user-images.githubusercontent.com/4155254/30348216-023eb3a0-97e5-11e7-95c1-7dbb38b91aec.PNG)

**Comment by cristijora** [comment]
@marcusos Thanks for posting and using the dashboard. 
You can quickly fix this by changing the z-index of the card-header or the z-index of the navbar

Option 1:
- Go to `_cards.scss` line 41 and change `z-index: 3;` to `z-index:1`

Option 2:
- Go to `_misc.scss` line 37 and change `z-index: 2;` to `z-index: 4`

We will add one of the 2 fixes in the next update.

**Comment by alexandru-paduraru** [comment]
@cristijora @marcusos yes, option 3 is the right one

**Comment by marcusos** [comment]
@cristijora thank you.

**Comment by cristijora** [comment]
This has been fixed and released in v1.1.0
Feel free to download the [New version here](https://www.creative-tim.com/product/vue-paper-dashboard-pro)

and follow along the [Migration tips](https://cristijora.github.io/paper-dashboard-pro/documentation.html?selectedKind=General%20tips&selectedStory=Migration%20guide&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel) from previous version to the new version.
