### ISSUE TITLE
Radio Component missing "inline" support

### ISSUE THREAD

**Issue by mmartinez0** [creativetimofficial/vue-paper-dashboard-pro#6]
Similar to checkbox I need to be able to inline a list group of radio components. I have included a picture of my fix.
![selection_009](https://user-images.githubusercontent.com/1011401/30377723-7072cb60-9856-11e7-8307-43f464c83177.png)

**Comment by cristijora** [comment]
@mmartinez0 Thanks a lot for pointing it out as well as showing the fix! 
Hope you enjoy the dashboard and it will help you build things faster

**Comment by cristijora** [comment]
This has been fixed and released in v1.1.0
Feel free to download the [New version here](https://www.creative-tim.com/product/vue-paper-dashboard-pro) and follow along the [Migration tips](https://cristijora.github.io/paper-dashboard-pro/documentation.html?selectedKind=General%20tips&selectedStory=Migration%20guide&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel) from previous version to the new version.
