### ISSUE TITLE
Alerts for global validation errors in forms

### ISSUE THREAD

**Issue by deivkk** [creativetimofficial/vue-paper-dashboard-pro#7]
Hi,

Forms support validation errors per field but I fail to find how to show an alert for a global validation error on top (e.g. classic alert for a login form: Invalid username or password). I have tried to add a div alert in the content card where the form is included without success.

Could you please provide me an example on how to achieve this?

Thanks

**Comment by cristijora** [comment]
Hi again @deivkk 

Depending on the text you want to show, you can do it in 2 ways but the principle would be the same.
For example if you want to show an error if username or password is incorrect which usually relies on a server request, I would set a new field inside data
```js
data(){
 return {
  hasServerError: false,
  serverErrorMessage: ''
 }
}
```
And set these when you do the login call.
```js
methods:{
 login(){
  axios.post(loginUrl, loginData)
  .then((data)=>{
   //decide here whether to set the error or not
  //as an example
  this.hasServerError = true
  this.serverErrorMessage = "Invalid username or password"
  })
  .catch((error)=>{
   //decide here whether to set the error or not
 })
 }
}
```

Then in your markup you could simply display a text message
```html
 <small class="text-danger" v-show="hasServerError">
      {{serverErrorMessage}}
</small>
```

If you simply want to display a general message that the user has to complete all fields you can do it like this:
```
<small class="text-danger" v-show="!isFormValid">
      Please validate all fields before submiting
</small>
```

```js
 computed: {
      isFormValid () {
        return this.errors.length === 0
      }
 },
```

I think you can also do async validations with vee-validate which is used in the dashboard. If I find it more intuitive I will write a solution here but until then you can easily stick with what I described.

**Comment by deivkk** [comment]
Thanks @cristijora for your quick answer.

Maybe I was not clear with my first message (sorry about that), but my problem was more related with the style. Moreover, the solution you proposed with the vue data is very similar to my current code, so I am glad to go in the right direction.

My idea was to show a red box with the alert inside. similar to this:
https://i.pinimg.com/736x/3a/fa/6b/3afa6bc5e13f56867f5cd308477b75d5--app-ui-design-interface-design.jpg

I tried to use a notification component like the danger alert under the Notification States section here: https://cristijora.github.io/paper-dashboard-pro/#/components/notifications, but I failed.

However your proposal of just showing just the text with no box around it seems cleaner and more aligned with the overall design.

**Comment by cristijora** [comment]
I think a danger text is more simple. It would also match other validations. 
As you said, you could also use 
https://cristijora.github.io/paper-dashboard-pro/#/components/notifications but it probably needs a bit of restyling to fit better in forms. Personally I wouldn't use that unless I have a very specific design which introduces such things. Sticking to something simple is always a good idea :)

**Comment by deivkk** [comment]
I couldn't agree more. Thanks!

**Comment by cristijora** [comment]
Glad I could help. Closing the issue.
