### ISSUE TITLE
Vee-validate Dependency Error

### ISSUE THREAD

**Issue by abdullahonden** [creativetimofficial/vue-paper-dashboard-pro#8]
One of the dependencies, "**vee-validate**" package 2.0.0-rc.15 causes a problem below:

RegisterForm.vue?56d3:57 Uncaught TypeError: (0 , _veeValidate.mapFields) is not a function
    at eval (RegisterForm.vue?56d3:57)
    at Object.<anonymous> (app.js:2267)
    at __webpack_require__ (app.js:689)
    at fn (app.js:110)
    at eval (RegisterForm.vue?1bc6:7)
    at Object.<anonymous> (app.js:3205)
    at __webpack_require__ (app.js:689)
    at fn (app.js:110)
    at eval (ValidationForms.vue?53ad:16)
    at Object.<anonymous> (app.js:2253)

Previous version 2.0.0-rc.14 has no problem. So we solved the problem by changing vee-validate package version to "2.0.0-rc.14".

Is there a bug of vee-validate package or implementing of it?

**Comment by leftbrainit** [comment]
Same issue here

**Comment by cristijora** [comment]
Hi @abdullahonden and @leftbrainit . Thanks for using the dashboard and for posting the issue.
I would advise to stick with the version which is provided in the package.json `2.0.0-rc.14`
This seems to be an issue from `vee-validate` itself
https://github.com/baianat/vee-validate/issues/827

**Comment by logaretm** [comment]
@cristijora Let me know if you find anything. its probably on my end here. I will release a quick fix once resolved.

**Comment by cristijora** [comment]
@logaretm Fixed it and will release a new version. Will close this issue as it's not related to the template anymore :)
