### ISSUE TITLE
MovingArrow not functioning

### ISSUE THREAD

**Issue by pierre-moire** [creativetimofficial/vue-paper-dashboard-pro#9]
In the free version sidebar's moving arrow was functioning and not in the pro version although the component is still present in the code. 

Can you fix this please ?

**Comment by cristijora** [comment]
@pierre-moire I will try to make it work. It might be harder to do it since the arrow is shown inside menus.

**Comment by pierre-moire** [comment]
Thanks ! Would it be easier by using the same approach as the free version (absolution positioning + css transition outside the menu itself) ?

**Comment by pierre-moire** [comment]
@cristijora  By the way, congratulations I love your product :)

**Comment by cristijora** [comment]
@pierre-moire Thanks a lot! Regarding the same approach, not really because the arrow is hidden when a menu is closed/collapsed. I will park this issue after resolving some other bugs and see if I can do something about it. Agree that it would be nice to have the arrow animated 😄

**Comment by alexandru-paduraru** [comment]
@pierre-moire @cristijora we have the logic that is behind, but it is written in jQuery, we used that for Material Dashboard PRO Angular. It was used for the Moving Tab, I think it has the same principle on the front end with the position absolute. The logic is so long because it has to check all the possible cases for the opened/closed collapsible elements. This is the code for the logic:

```javascript
mda = {
    misc: {
        movingTab: '<div class="sidebar-moving-tab"/>',
        isChild: false,
        sidebarMenuActive: ''
    }
 };

var sidebarTimer;

$(document).ready(function(){

    mda.misc.movingTab = $(mda.misc.movingTab);

    mda.misc.sidebarMenuActive = $('.sidebar .nav-container > .nav > li.active > a:not([data-toggle="collapse"]');

    if(mda.misc.sidebarMenuActive.length != 0){
        setMovingTabPosition(mda.misc.sidebarMenuActive);
    } else {
        mda.misc.sidebarMenuActive = $('.sidebar .nav-container .nav > li.active .collapse li.active > a');
        mda.misc.isChild = true;
        setParentCollapse();
    }

    mda.misc.sidebarMenuActive.parent().addClass('visible');
    $('.sidebar .nav-container').append(mda.misc.movingTab);

    if (window.history && window.history.pushState) {
        $(window).on('popstate', function() {

            setTimeout(function(){
                mda.misc.sidebarMenuActive = $('.sidebar .nav-container .nav li.active a:not([data-toggle="collapse"])');

                if(mda.misc.isChild == true){
                    setParentCollapse();
                }
                animateMovingTab();
            },10);

        });
    }

    $('.sidebar .nav .collapse').on('hidden.bs.collapse', function () {
        setMovingTabPosition();
    });

    $('.sidebar .nav .collapse').on('shown.bs.collapse', function () {
        setMovingTabPosition();
    });

});

$('.sidebar .nav-container .nav > li > a:not([data-toggle="collapse"])').click(function(){
    mda.misc.sidebarMenuActive = $(this);
    $parent = $(this).parent();

    if(mda.misc.sidebarMenuActive.closest('.collapse').length == 0){
        mda.misc.isChild = false;
    }

    // we call the animation of the moving tab
    animateMovingTab();
});

function animateMovingTab(){
    clearTimeout(sidebarTimer);

    $currentActive = mda.misc.sidebarMenuActive;

    $('.sidebar .nav-container .nav li').removeClass('visible');

    $movingTab = mda.misc.movingTab;
    $movingTab.addClass('moving');

    $movingTab.css('padding-left',$currentActive.css('padding-left'));
    var button_text = $currentActive.html();

    setMovingTabPosition($currentActive);

    sidebarTimer = setTimeout(function(){
        $movingTab.removeClass('moving');
        $currentActive.parent().addClass('visible');
    }, 650);

    setTimeout(function(){
        $movingTab.html(button_text);
    }, 10);
}

function setMovingTabPosition(){
    $currentActive = mda.misc.sidebarMenuActive;
    li_distance = $currentActive.parent().position().top - 10;

    if($currentActive.closest('.collapse').length != 0){
        parent_distance = $currentActive.closest('.collapse').parent().position().top;
        li_distance = li_distance + parent_distance;
    }

    mda.misc.movingTab.css({
        'transform':'translate3d(0px,' + li_distance + 'px, 0)'
    });
}
function setParentCollapse(){
    if(mda.misc.isChild == true){
        $sidebarParent = mda.misc.sidebarMenuActive.parent().parent().parent();
        var collapseId = $sidebarParent.siblings('a').attr("href");

        $(collapseId).collapse("show");

        $(collapseId).collapse()
        .on('shown.bs.collapse', function (){
            setMovingTabPosition();
        })
        .on('hidden.bs.collapse', function(){
            setMovingTabPosition();
        });

    }
}

```
@cristijora: The current code is the best option that we found. I will let this here. We will have a look together on this and I will explain why it is so long and if we find a better way for Vue we will do that.

@pierre-moire we will have this fixed in one of the next releases.

**Comment by pierre-moire** [comment]
@alexandru-paduraru Great thanks !

**Comment by cristijora** [comment]
damn @alexandru-paduraru that's pretty complicated 😄 
The arrow in the free version is very simple
https://github.com/cristijora/vue-paper-dashboard/blob/master/src/components/UIComponents/SidebarPlugin/MovingArrow.vue

We can go through that code once we fix the other minor issues/bugs.

**Comment by alexandru-paduraru** [comment]
@cristijora yeah...I know it's long and ugly :-))) but that was the best option. I also know the code is very simple for the free, it was very simple for our Material Dashboard Free too, it didn't have any jQuery. 

I will explain which are the problems when you work with collapse elements and what happens if you move from a child of a collapse to another child of another collapse, that is the biggest issue. Or when you move from a parent to a child. I hope we will find a better way to do this.

**Comment by cristijora** [comment]
Hey @alexandru-paduraru @pierre-moire I managed to do it in a fairly simple way.
```html
<moving-arrow v-show="showMovingArrow" :initialize="initializeArrow"></moving-arrow>
```
```js
// inside initScrollBar
 PerfectScroll.initialize(this.$refs.sidebarScrollArea)
 this.initializeArrow = true
```

```js
//MovingArrow.vue
export default {
    props: {
      initialize: Boolean
    },
    data () {
      return {
        toMove: 0,
        linkActiveClass: 'router-link-exact-active',
        displayArrow: false
      }
    },
    computed: {
      arrowStyle () {
        let styles = {
          transform: `translate3d(0px, ${this.toMove}px, 0px)`,
          opacity: this.displayArrow ? 1 : 0
        }
        if (this.toMove !== 0) {
          styles.top = '0px'
        }
        return styles
      }
    },
    methods: {
      calculateTopOffset () {
        this.displayArrow = true
        const scrollEl = document.querySelector('.ps__scrollbar-y-rail')
        const activeRouteLink = document.querySelector(`.sidebar .${this.linkActiveClass}`)
        const routeLinkTop = activeRouteLink.getBoundingClientRect().top
        this.toMove = scrollEl.offsetTop + routeLinkTop - 75
      }
    },
    watch: {
      $route (newVal, oldVal) {
        this.calculateTopOffset()
      },
      initialize (newVal) {
        if (newVal) {
          this.calculateTopOffset()
        }
      }
    }
  }
```

This works fairly well and the arrow moves smoothly. It doesn't treat the case where it should hide the arrow if you close the menu where the arrow is but that can be done easily by setting `showMovingArrow` to false when that happens.

This works mainly based on `calculateTopOffset` which calculates the position where the arrow should be. It takes the perfect scrollbar top offset + the active link element based on a css class which in our case is set by vue router. The position is recalculated upon route changes
```
$route (newVal, oldVal) {
    this.calculateTopOffset()
 },
```

**Comment by cristijora** [comment]
Realized this wouldn't work on mobile as it might need other tweaks. @alexandru-paduraru Is it ok if it works on desktop only?

**Comment by alexandru-paduraru** [comment]
@cristijora it looks like a pretty good solution. We can go only with the desktop, in the beginning, then we see what we can do for mobile. Maybe we can add it on a new branch so I can check some use cases. We have to think also for the case when we are not using perfectScrollbar in Mac OS.

**Comment by cristijora** [comment]
Oh alright. I put it in a new branch already as it was not complete yet.

**Comment by cristijora** [comment]
@pierre-moire Unfortunately the support for moving arrow was dropped in the PRO theme as it became overly complicated to do it and was sensitive to bugs. Removing the moving arrow support cleaned up almost half of the code from Sidebar plugin which I think is more important than having a little nice feature such as this one.
